alias sourcep='source ~/.profile'
alias nvims='nvim ~/.config/nvim'
alias nvima='nvim ~/.config/alacritty/alacritty.yml'
alias nvimp='nvim ~/.profile'
alias nvimc='nvim .'
alias nvimt='nvim ~/.tmux.conf'
alias tmuxn='tmux new -s'
alias tmuxa='tmux a -t'
alias tmuxl='tmux ls'
alias tmuxr='tmux source ~/.tmux.conf'
alias tmuxk='tmux kill-session'
alias tmuxe='tmux kill-session -a -t'

