import = [ '~/.config/alacritty/themes/themes/tokyo-night-storm.toml' ]

[env]
TERM = 'xterm-256color'

[window]
startup_mode = 'Fullscreen'
padding.x = 10
padding.y = 10
decorations = 'Buttonless'
opacity = 0.8
blur = true
option_as_alt = 'Both'

[font]
# 3270, BigBlueTermPlus, Hack Nerd Font Mono, MesloLGL, NotoSansM, ProFontWindows, ProFont IIx
normal.family = 'MesloLGL Nerd Font'
size = 14
