#!/bin/bash

# Set profile path
PROFILE='.bash_profile'
if [ -f '~/.profile' ]; then
    PROFILE='.profile'
fi

# Set messages to print
COPYING_ALACRITTY="Copying alacritty.toml to ~/.config/alacritty/alacritty.toml"
PROFILE_ALACRITTY="alacritty.toml copied to ~/.config/alacritty/alacritty.toml successfully"
COPYING_P10K='Copying .p10k.zsh to ~/.p10k.zsh'
P10K_COPIED='.p10k.zsh copied to ~/.p10k.zsh successfully'
COPYING_PROFILE="Copying $PROFILE to ~/$PROFILE"
PROFILE_COPIED="$PROFILE copied to ~/$PROFILE successfully"
COPYING_TMUX='Copying .tmux.conf to ~/.tmux.conf'
TMUX_COPIED='.tmux.conf copied to ~/.tmux.conf successfully'
USAGE="Usage: $(basename $0) [-p] [-t]"

# Copy all files by default
if [ "$#" -lt 1 ]; then
    echo $COPYING_ALACRITTY
    cp ./.alacritty.toml ~/.config/alacritty/alacritty.toml
    echo $PROFILE_ALACRITTY
    echo $COPYING_P10K
    cp ./.p10k.zsh ~/.p10k.zsh
    echo $P10K_COPIED
    echo $COPYING_PROFILE
    cp ./$PROFILE ~/$PROFILE
    echo $PROFILE_COPIED
    echo $COPYING_TMUX
    cp .tmux.conf ~/
    echo $TMUX_COPIED
    exit 1
fi

# Parse arguments
while getopts 'akpth' opt; do
    case "$opt" in
        a)
            echo $COPYING_ALACRITTY
            cp ./.alacritty.toml ~/.config/alacritty/alacritty.toml
            echo $PROFILE_ALACRITTY
            ;;
        k)
            echo $COPYING_P10K
            cp ./.p10k.zsh ~/.p10k.zsh
            echo $P10K_COPIED
            ;;
        p)
            echo $COPYING_PROFILE
            cp ./$PROFILE ~/$PROFILE
            echo $PROFILE_COPIED
            ;;
        t)
            echo $COPYING_TMUX
            cp .tmux.conf ~/
            echo $TMUX_COPIED
            ;;
        h)
            echo $USAGE
            ;;
        ?)
            echo -e 'Invalid command option'
            exit 1
            ;;
    esac
done
shift "$(($OPTIND -1))"
